/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const create_encoded: (a: number, b: number, c: number, d: number) => [number, number, number];
export const generate_register_envelope: (a: number, b: number) => [number, number, number];
export const read_encoded: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => [number, number, number, number];
export const __wbg_encoded_free: (a: number, b: number) => void;
export const __wbg_get_encoded_enc_kyber: (a: number) => [number, number];
export const __wbg_get_encoded_enc_nonce: (a: number) => [number, number];
export const __wbg_get_encoded_encoded: (a: number) => [number, number];
export const __wbg_set_encoded_enc_kyber: (a: number, b: number, c: number) => void;
export const __wbg_set_encoded_enc_nonce: (a: number, b: number, c: number) => void;
export const __wbg_set_encoded_encoded: (a: number, b: number, c: number) => void;
export const encoded_new: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const __wbg_get_registerenvelope_enc_sk: (a: number) => [number, number];
export const __wbg_get_registerenvelope_master_salt: (a: number) => [number, number];
export const __wbg_get_registerenvelope_pk: (a: number) => [number, number];
export const __wbg_get_registerenvelope_sk_nonce: (a: number) => [number, number];
export const __wbg_registerenvelope_free: (a: number, b: number) => void;
export const __wbg_set_registerenvelope_enc_sk: (a: number, b: number, c: number) => void;
export const __wbg_set_registerenvelope_master_salt: (a: number, b: number, c: number) => void;
export const __wbg_set_registerenvelope_pk: (a: number, b: number, c: number) => void;
export const __wbg_set_registerenvelope_sk_nonce: (a: number, b: number, c: number) => void;
export const registerenvelope_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
